name: erba_coders
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1


# ---- PACKAGES ---- #

dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product specific


# ---- END PACKAGES ---- #


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  
  # ---- LOCAL ASSETS ---- #
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/


  # ---- LOCAL FONTS ---- #
  fonts:
    - family: MADE Envolve Sans
      fonts:
        - asset: assets/fonts/made_evolve_sans/MADE Evolve Sans Thin.otf
          weight: 200
        - asset: assets/fonts/made_evolve_sans/MADE Evolve Sans Light.otf
          weight: 300
        - asset: assets/fonts/made_evolve_sans/MADE Evolve Sans Regular.otf
          weight: 400
        - asset: assets/fonts/made_evolve_sans/MADE Evolve Sans Medium.otf
          weight: 500
        - asset: assets/fonts/made_evolve_sans/MADE Evolve Sans Bold.otf
          weight: 800
        - asset: assets/fonts/made_evolve_sans/MADE Evolve Sans Thin EVO.otf
          weight: 200
        - asset: assets/fonts/made_evolve_sans/MADE Evolve Sans Light EVO.otf
          weight: 300
        - asset: assets/fonts/made_evolve_sans/MADE Evolve Sans Regular EVO.otf
          weight: 400
        - asset: assets/fonts/made_evolve_sans/MADE Evolve Sans Medium EVO.otf
          weight: 500
        - asset: assets/fonts/made_evolve_sans/MADE Evolve Sans Bold EVO.otf
          weight: 800